"use client"

import { useState } from 'react'
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { usePathname } from 'next/navigation';
// import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function AuthLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>)

{
  const [input, setInput] = useState("")
  const pathName = usePathname()
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div>
          <input type="text" value={input} onChange={(e) => setInput(e.target.value)} />
        </div>
        <h1>Auth layout</h1>
        {children}
      </body>
    </html>
  );
}
